spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
logging:
  level:
    org:
      springframework: WARN